language: generic 
sudo: require
services:
  - docker

before_install:
  - docker build -t caioaanolasco/docker-react -f Dockerfile.dev .

script:
  - docker run caioaanolasco/docker-react npm run test -- --coverage